version: '2.0'

services:
  prometheus: 
    image: prom/prometheus:v1.0.1
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_data:/prometheus
        - ./alert.rules:/etc/prometheus/alert.rules
    command:
        - '-config.file=/etc/prometheus/prometheus.yml'
        - '-alertmanager.url=http://alertmanager:9093'
    ports:
        - '9090:9090'

  grafana:
    image: "grafana/grafana:3.1.1"
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
        - prometheus
    volumes:
        - grafana_data:/var/lib/grafana
        - ./alert.rules:/etc/prometheus/alert.rules
    ports:
        - "3000:3000"

  alertmanager:
    image: "prom/alertmanager:v0.8.0"
    volumes:
        - ./alertmanager.yml:/alertmanager.yml
    command:
        - '-config.file=/alertmanager.yml'
    
volumes:
  prometheus_data: {}
  grafana_data: {}
